### ISSUE TITLE
Non-existent class: CI_Encryption

### ISSUE THREAD

**Issue by rrcc0044** [kenjis/ci-phpunit-test#143]
I followed the installation guide using --dev, run phpunit and got this error

```
An uncaught Exception was encountered

Type:        CIPHPUnitTestShowErrorException
Message:     Non-existent class: CI_Encryption
Filename:    /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Common.php
Line Number: 178

Backtrace:
    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 1265
    Function: show_error

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 1161
    Function: _ci_init_library

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 1052
    Function: _ci_load_stock_library

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 218
    Function: _ci_load_library

    File: /opt/lampp/htdocs/api/application/helpers/autoload_helper.php
    Line: 6
    Function: library

    File: /opt/lampp/htdocs/api/application/config/database.php
    Line: 114
    Function: get

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 395
    Function: DB

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 1367
    Function: database

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/replacing/core/Loader.php
    Line: 157
    Function: _ci_autoloader

    File: /opt/lampp/htdocs/api/application/tests/_ci_phpunit_test/CIPHPUnitTest.php
    Line: 77
    Function: __construct

    File: /opt/lampp/htdocs/api/application/tests/Bootstrap.php
    Line: 361
    Function: init

    File: phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php
    Line: 56
    Function: include_once

    File: phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php
    Line: 38
    Function: load

    File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
    Line: 902
    Function: checkAndLoad

    File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
    Line: 731
    Function: handleBootstrap

    File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
    Line: 126
    Function: handleArguments

    File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
    Line: 115
    Function: run

    File: /usr/local/bin/phpunit
    Line: 572
    Function: main
```

**Comment by kenjis** [comment]
I don't know why.
Would you show me how do you install CodeIgniter, PHPUnit and ci-phpunit-test?

**Comment by h4km** [comment]
I have same error like this?

D:\xampp\htdocs\ci-inventori\application\tests\controllers (jono)
λ phpunit Welcome_test.php
PHP Fatal error:  Class 'TestCase' not found in D:\xampp\htdocs\ci-inventori\application\tests\controllers\Welcome_test.php on line 12

Fatal error: Class 'TestCase' not found in D:\xampp\htdocs\ci-inventori\application\tests\controllers\Welcome_test.php on line 12

**Comment by OlexandrPopov** [comment]
I assume the issue is related to the loading of the stock libraries with alternative names. In my case I have autoload.php with the following lines:

```
$autoload['libraries'] = [
	['MyEventDispatcher' => 'eventDispatcher'],
	['form_validation' => 'formValidation']
];
```

When I run test I get the "Non-existent class: CI_Form_validation" error with the similar backtrace:

```
An uncaught Exception was encountered

Type:        CIPHPUnitTestShowErrorException
Message:     Non-existent class: CI_Form_validation
Filename:    C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Common.php
Line Number: 178

Backtrace:
        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 1314
        Function: show_error

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 1179
        Function: _ci_init_library

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 1091
        Function: _ci_load_stock_library

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 226
        Function: _ci_load_library

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 214
        Function: library

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 210
        Function: library

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 1423
        Function: library

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\replacing\core\Loader.php
        Line: 161
        Function: _ci_autoloader

        File: C:\Users\popov_000\projects\myproject\application\core\MY_Loader.php
        Line: 24
        Function: initialize

        File: C:\Users\popov_000\projects\myproject\application\tests\_ci_phpunit_test\CIPHPUnitTest.php
        Line: 78
        Function: __construct

        File: C:\Users\popov_000\projects\myproject\application\tests\Bootstrap.php
        Line: 369
        Function: init

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\src\Util\Fileloader.php
        Line: 61
        Function: include_once

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\src\Util\Fileloader.php
        Line: 45
        Function: load

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\src\TextUI\Command.php
        Line: 908
        Function: checkAndLoad

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\src\TextUI\Command.php
        Line: 730
        Function: handleBootstrap

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\src\TextUI\Command.php
        Line: 151
        Function: handleArguments

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\src\TextUI\Command.php
        Line: 140
        Function: run

        File: C:\Users\popov_000\projects\myproject\vendor\phpunit\phpunit\phpunit
        Line: 53
        Function: main
```

I think this issue is related to [this one](https://github.com/kenjis/ci-phpunit-test/commit/e5b7a254440e38ffbad667bae97aa24d616afa56) and to solve it the 1164 line of the application/tests/_ci_phpunit_test/replacing/core/Loader.php should be uncomment:

`//		if (class_exists($prefix.$library_name, FALSE))`
