### ISSUE TITLE
Cannot decode output to JSON

### ISSUE THREAD

**Issue by MasonFI** [kenjis/ci-phpunit-test#167]
Hi,

```php
$output = $this->request('GET', '/api/v1/events');
$this->assertResponseCode(200);
$outputObj = json_decode((string) $output);
$this->assertObjectHasAttribute('resources', $outputObj);
```

Somehow `$outputObj` is always null. This the `$output` (fetched from DB, created by Faker):
`
{"resources":[{"eventID":"04229ff3-1754-3576-a9bc-bf07703969f4","name":"Opera\/8.27 (Windows NT 6.1; en-US) Presto\/2.12.164 Version\/12.00","description":"Odio nemo est enim fugiat nemo ut voluptatum. Molestiae aut delectus voluptas explicabo et ea omnis. Consequatur assumenda consectetur nobis tempore. Placeat quia ullam rerum.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"746","participantsRegistered":"0","organizationID":"7b426848-f094-3212-bd47-a0b12e0edaa8","published":"1","eventURL":"89547f6de8b586d83e4f208a96788863","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 10:02:40","href":"http:\/\/localhost\/api\/v1\/events"},{"eventID":"08e4efa2-c7fa-3eb2-9454-2673a81b5cbd","name":"Opera\/9.23 (Windows 95; en-US) Presto\/2.10.298 Version\/10.00","description":"Aut occaecati voluptas mollitia cupiditate enim accusantium. Quos quis vero sit. Delectus harum minus quo et. Quos eligendi voluptatem minus. Officiis ut ut voluptatem.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"455","participantsRegistered":"0","organizationID":"7b426848-f094-3212-bd47-a0b12e0edaa8","published":"1","eventURL":"90ce5082efb63d1d67b3b7872f3811c6","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 10:02:40","href":"http:\/\/localhost\/api\/v1\/events"}]}
`

Online JSON validator says its valid JSON. I even tried utf8_encode for the string but it does not help. 
If I copy-paste that string to json_decode() manually, it works.

Heres the Events.php controller for endpoint:
```php
$resource = $this->EventsManager->findOneBy('eventID', $id);
$response = array('resources' => array($resource));
$this->set_response($response, RESTController::HTTP_OK);
```

Any ideas what's wrong with my code?

**Comment by kenjis** [comment]
@MasonFI 

I copied your json output:
```php
<?php
$output = '{"resources":[{"eventID":"04229ff3-1754-3576-a9bc-bf07703969f4","name":"Opera\/8.27 (Windows NT 6.1; en-US) Presto\/2.12.164 Version\/12.00","description":"Odio nemo est enim fugiat nemo ut voluptatum. Molestiae aut delectus voluptas explicabo et ea omnis. Consequatur assumenda consectetur nobis tempore. Placeat quia ullam rerum.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"746","participantsRegistered":"0","organizationID":"7b426848-f094-3212-bd47-a0b12e0edaa8","published":"1","eventURL":"89547f6de8b586d83e4f208a96788863","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 10:02:40","href":"http:\/\/localhost\/api\/v1\/events"},{"eventID":"08e4efa2-c7fa-3eb2-9454-2673a81b5cbd","name":"Opera\/9.23 (Windows 95; en-US) Presto\/2.10.298 Version\/10.00","description":"Aut occaecati voluptas mollitia cupiditate enim accusantium. Quos quis vero sit. Delectus harum minus quo et. Quos eligendi voluptatem minus. Officiis ut ut voluptatem.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"455","participantsRegistered":"0","organizationID":"7b426848-f094-3212-bd47-a0b12e0edaa8","published":"1","eventURL":"90ce5082efb63d1d67b3b7872f3811c6","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 10:02:40","href":"http:\/\/localhost\/api\/v1\/events"}]}';

$outputObj = json_decode((string) $output);
var_dump($outputObj);
```

No problem on my environment:
```
$ php test.php 
object(stdClass)#3 (1) {
  ["resources"]=>
  array(2) {
    [0]=>
    object(stdClass)#1 (18) {
      ["eventID"]=>
      string(36) "04229ff3-1754-3576-a9bc-bf07703969f4"
      ["name"]=>
      string(64) "Opera/8.27 (Windows NT 6.1; en-US) Presto/2.12.164 Version/12.00"
      ["description"]=>
      string(175) "Odio nemo est enim fugiat nemo ut voluptatum. Molestiae aut delectus voluptas explicabo et ea omnis. Consequatur assumenda consectetur nobis tempore. Placeat quia ullam rerum."
      ["eventStarts"]=>
      string(19) "0000-00-00 00:00:00"
      ["eventEnds"]=>
      string(19) "0000-00-00 00:00:00"
      ["signUpStarts"]=>
      NULL
      ["signUpEnds"]=>
      NULL
      ["participantsMax"]=>
      string(3) "746"
      ["participantsRegistered"]=>
      string(1) "0"
      ["organizationID"]=>
      string(36) "7b426848-f094-3212-bd47-a0b12e0edaa8"
      ["published"]=>
      string(1) "1"
      ["eventURL"]=>
      string(32) "89547f6de8b586d83e4f208a96788863"
      ["materialUpload"]=>
      string(1) "0"
      ["materialUploadStarts"]=>
      NULL
      ["materialUploadEnds"]=>
      NULL
      ["timeModified"]=>
      NULL
      ["timeCreated"]=>
      string(19) "2017-02-08 10:02:40"
      ["href"]=>
      string(30) "http://localhost/api/v1/events"
    }
    [1]=>
    object(stdClass)#2 (18) {
      ["eventID"]=>
      string(36) "08e4efa2-c7fa-3eb2-9454-2673a81b5cbd"
      ["name"]=>
      string(60) "Opera/9.23 (Windows 95; en-US) Presto/2.10.298 Version/10.00"
      ["description"]=>
      string(168) "Aut occaecati voluptas mollitia cupiditate enim accusantium. Quos quis vero sit. Delectus harum minus quo et. Quos eligendi voluptatem minus. Officiis ut ut voluptatem."
      ["eventStarts"]=>
      string(19) "0000-00-00 00:00:00"
      ["eventEnds"]=>
      string(19) "0000-00-00 00:00:00"
      ["signUpStarts"]=>
      NULL
      ["signUpEnds"]=>
      NULL
      ["participantsMax"]=>
      string(3) "455"
      ["participantsRegistered"]=>
      string(1) "0"
      ["organizationID"]=>
      string(36) "7b426848-f094-3212-bd47-a0b12e0edaa8"
      ["published"]=>
      string(1) "1"
      ["eventURL"]=>
      string(32) "90ce5082efb63d1d67b3b7872f3811c6"
      ["materialUpload"]=>
      string(1) "0"
      ["materialUploadStarts"]=>
      NULL
      ["materialUploadEnds"]=>
      NULL
      ["timeModified"]=>
      NULL
      ["timeCreated"]=>
      string(19) "2017-02-08 10:02:40"
      ["href"]=>
      string(30) "http://localhost/api/v1/events"
    }
  }
}
```

```
PHP 7.0.5 (cli) (built: Mar 31 2016 06:38:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by MasonFI** [comment]
Hi,

Yes my code also works if I copy it manually to json_encode. Weird.

**Comment by kenjis** [comment]
@MasonFI 

```php
$output = $this->request('GET', '/api/v1/events');
var_dump($ouput);
```
The code above shows the json string?

**Comment by MasonFI** [comment]
Yes, it shows the same json string that is mentioned above.

**Comment by kenjis** [comment]
Very wired. I have no idea.

**Comment by MasonFI** [comment]
It seems I was wrong with the given output. I used file_put_contents to get the real output and it shows this:
```
A PHP Error was encountered

Severity:    Warning
Message:     Cannot modify header information - headers already sent by (output started at /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Util/Printer.php:114)
Filename:    /var/www/api.eventos2.local/app/application/libraries/RESTController.php
Line Number: 2239

Backtrace:
        File: /var/www/api.eventos2.local/app/application/libraries/RESTController.php
        Line: 2239
        Function: header

        File: /var/www/api.eventos2.local/app/application/libraries/RESTController.php
        Line: 460
        Function: _check_cors

        File: /var/www/api.eventos2.local/app/application/libraries/RESTProxyController.php
        Line: 35
        Function: __construct

        File: /var/www/api.eventos2.local/app/application/controllers/api/v1/Events.php
        Line: 26
        Function: __construct

        File: /var/www/api.eventos2.local/app/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
        Line: 312
        Function: __construct

        File: /var/www/api.eventos2.local/app/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
        Line: 266
        Function: createAndCallController

        File: /var/www/api.eventos2.local/app/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
        Line: 141
        Function: requestUri

        File: /var/www/api.eventos2.local/app/tests/_ci_phpunit_test/CIPHPUnitTestCase.php
        Line: 136
        Function: request

        File: /var/www/api.eventos2.local/app/tests/integration/api/v1/EventsTest.php
        Line: 16
        Function: request

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestCase.php
        Line: 1121
        Function: invokeArgs

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestCase.php
        Line: 972
        Function: runTest

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestResult.php
        Line: 709
        Function: runBare

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestCase.php
        Line: 927
        Function: run

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestSuite.php
        Line: 728
        Function: run

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestSuite.php
        Line: 728
        Function: run

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/Framework/TestSuite.php
        Line: 728
        Function: run

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/TextUI/TestRunner.php
        Line: 491
        Function: run

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/TextUI/Command.php
        Line: 188
        Function: doRun

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/src/TextUI/Command.php
        Line: 118
        Function: run

        File: /var/www/api.eventos2.local/vendor/phpunit/phpunit/phpunit
        Line: 52
        Function: main


{"resources":[{"eventID":"b32a3f76-1b50-334e-ae62-179390350732","name":"Opera\/9.32 (Windows NT 6.2; en-US) Presto\/2.11.238 Version\/12.00","description":"Molestias et architecto voluptas similique. Eum dolorem aut quo illo modi adipisci id. Dignissimos perferendis vitae voluptatem labore nobis. Ipsam dolorem labore modi ea repudiandae.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"95","participantsRegistered":"0","organizationID":"cc9bfe37-6324-37aa-b869-894d038649a7","published":"0","eventURL":"266379c481e4d29d6723592f734192db","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 11:48:42","href":"http:\/\/localhost\/api\/v1\/events"},{"eventID":"6104b829-cac3-3479-ae44-3eade4b08d7b","name":"Opera\/8.54 (X11; Linux x86_64; en-US) Presto\/2.12.233 Version\/12.00","description":"Impedit facere et deserunt sit sit occaecati. Non ad consequatur voluptatem molestiae expedita numquam voluptas natus. Incidunt incidunt aut vero porro illo.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"899","participantsRegistered":"0","organizationID":"cc9bfe37-6324-37aa-b869-894d038649a7","published":"1","eventURL":"ecec5b5e68ee72b7c9b31e8613a29742","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 11:48:42","href":"http:\/\/localhost\/api\/v1\/events"},{"eventID":"86dd4f74-5512-3e4e-9775-b6dce80436bf","name":"Prospectum event","description":"Consectetur quia voluptatem quia fugit. Ullam reiciendis maiores sit repudiandae. Occaecati eos voluptatum omnis ullam.","eventStarts":"0000-00-00 00:00:00","eventEnds":"0000-00-00 00:00:00","signUpStarts":null,"signUpEnds":null,"participantsMax":"883","participantsRegistered":"0","organizationID":"cc9bfe37-6324-37aa-b869-894d038649a7","published":"1","eventURL":"ff40b2a383b4dcbeb3618c497b1e738f","materialUpload":"0","materialUploadStarts":null,"materialUploadEnds":null,"timeModified":null,"timeCreated":"2017-02-08 11:48:42","href":"http:\/\/localhost\/api\/v1\/events"}]}
```
